# Generated by Django 4.2.2 on 2023-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
            ],
        ),
    ]
