# Generated by Django 4.2.2 on 2023-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Image',
            field=models.FileField(upload_to='media'),
        ),
    ]
