# Generated by Django 4.2.2 on 2023-06-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='media')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
            ],
        ),
    ]
