# Generated by Django 4.2.2 on 2023-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Image',
            field=models.FileField(upload_to='myproject\\myapp\\static\\images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.FileField(upload_to='myproject\\myapp\\static\\images'),
        ),
    ]
