# Generated by Django 4.2.2 on 2023-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(upload_to='myproject/myapp/static/images'),
        ),
    ]
