# Generated by Django 4.2.2 on 2023-06-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Image',
            field=models.FileField(upload_to='\\static\\images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(upload_to='\\static\\images'),
        ),
    ]
