# Generated by Django 4.2.2 on 2023-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_cart_image_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Image',
            field=models.FileField(upload_to='myproject\\myapp\\static\\images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(upload_to='myproject/myapp/static/images'),
        ),
    ]
